### ISSUE TITLE
Implement react-select as a react-jsonschema-form widget

### ISSUE THREAD

**Issue by mattmonihan** [VoyagerScientific/react-jsonschema-form-widgets#2]
This job is to produce a React.js component that wraps the react-select(https://react-select.com/home) component and makes it accessible to the react-jsonschema-form library.

A basic example of how to create a custom widget is documented here: https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-component-registration

Here's a list of features we'd want to cover:

Boolean: for clearable
Boolean: for searchable
map the enum and enumNames objects that come from react-jsonschema-form to an object for react-select.
Boolean: for creatable, so the user can enter a value not included the select.
The component updates the parent with the onChange method that is include in props.

react-jsonschema-form: https://github.com/mozilla-services/react-jsonschema-form

#### Additional Info

There is a library called react-select that has a nice drop down with some additional features. I would like to be able to use that as a "widget" in the react-jsonschema-form library. So when you select something with the react-select component, it uses the onChange function which is provided by props in the from react-jsonschema-form to update the formData object which is logged in the console.

If you open up the demo page, you'll see a field that formats currency and when you change the value, you'll see the value in the formData object in the console.

With the react-select library, I'd like to be able to search values, and also use the create a new value functionality so a user could enter their own value if what they typed is not available.

**Comment by kandibolotskaya** [comment]
Done and created a new branch. Please check it

**Comment by mattmonihan** [comment]
Good start. 

 - Why does there need to be a WidgetWrapper component to wrap ReactSelectForm?
 - Why does the options variable need to be wrapped in a promise with a timeout.

Some things that we need to complete this task:
- When a form is loaded with formData(i.e. when you're editing an already submitted form), we need to bring that in through props. You can see in the currency widget that it comes in from `props.value`.
- I'd like the `clearable`, and `searchable`, `isMulti`, and [createable](https://react-select.com/creatable) options enabled with boolean values.

All options can be passed by adding "ui:options" to the currency object in uiSchema like so:
```json
uiSchema = {
  "test_react_select": {
    "ui:widget": "WidgetWrapper",
    "ui:options": {
      "react-select": {
        "clearable": true,
        "searchable": true,
        "isMulti" : true
     }
    }
  }
};

```
Here are the props for react-select so you can see what to map to: https://react-select.com/props

- If multi is enabled, we need to switch the field type in the schema to array. This would be known ahead of time, so create another object in the schema like so:

```json
schema: {
  "test_multi_select": {
      "type": "array",
       "items": {
          "type": "object",
          "properties": {
            "select_value": {
             "type": "string"
            }
        }
      }
   }
}
```

And then pass the `isMulti` option as part of the uiSchema like above. In this situation, we'd be sending an array of strings back to `onChange`.

It's likely there will need to be some kind of if statement to switch between whether you'll need the `Createable` component `Async`, etc.

**Comment by kandibolotskaya** [comment]
@mattmonihan 

> -Why does there need to be a WidgetWrapper component to wrap ReactSelectForm?

I suggested to create High Order Component, but for now it's unnecessary solution. So I left it for future architecture usage. That's why we have WidgetWrapper component. 

> -Why does the options variable need to be wrapped in a promise with a timeout.

I'm suggesting (correct me if I'm wrong) that we're going to have the API further. I'm going to send a requests to the API, and going to get them asynchronously. So I add promise as well.
I think the best way is to use fetch, axios, redux-saga or rx.js. 
So now it's a simulation of asynchronous request. 

Could you please describe your plans regarding API or architecture?

**Comment by mattmonihan** [comment]
Understood. We don't need the higher order component for now since each widget needs to be registered individually like we do in app.js. (const widgets = {})

Good idea with the promise. We'll be likely getting those options from the Airtable API. But we're not there yet, so we can wait.

**Comment by mattmonihan** [comment]
It's not necessary to have all these components wrapped in in the WidgetWrapper container. That should be discarded. I should be more clear about how these are used in context.
According to the [react-jsonschema-form docs](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/), there are the concepts of `Fields`, `Templates` and `Widgets`. The components folder should be structured with folders for each of those.

Looking at the documentation, the react-select component should likely be a widget when it's a string because it's only changing what's in the input area of the react-jsonschema-form component. So there should just be one file for `ReactSelect` in the /components/widgets folder, and that gets imported in the app.js file.

We need to use the registration style of including fields and widgets because the schema will be coming from a database, and saving functions as the value isn't valid json, or desired, because the implementation of the fields should stay in the codebase. H[ere's a link to how that looks](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-component-registration), and it's the same in the master branch.

The array version of the checkbox will be a little different, but I think this is how this works. Using [this json format](https://react-jsonschema-form.readthedocs.io/en/latest/form-customization/#multiple-choice-list) you can overwrite the `ui:field` and use the react select, but with different options.

For example:
```json
schema: {
  "test_multi_select": {
      "type": "array",
       "items": {
          "type": "string",
          "enum": ["1", "2", "3"],
          "enumNames": ["One", "Two", "Three"]
      }
   }
}

uiSchema: {
  "test_multi_select": {
    "ui:field": "ReactMultiSelect",
    "ui:options": {
      "react-select": {
        "isMulti" : true
     }
    }
  }
};
```
Apologies, I think I made a mistake when I gave you the first definition of the array. I think both could work, but this may be easier to customize.

The multi select should return an array with the chosen options. `[1, 3]`. I'm not sure if it should be a field or a widget, but you should try with a widget first because it's the least invasive.

[This page](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#advanced-customization) can help you decide:

![Screen Shot 2019-07-17 at 8 56 46 AM](https://user-images.githubusercontent.com/1066222/61377316-f4e59180-a870-11e9-9120-11e3de0bff1c.png)

--------

ant-design is ok to use for some of the presentation in app.js, but I can't use it in the final project, so it shouldn't be used in any the fields or widgets, so it probably shouldn't be used at all.
